image:
  name: alpine:latest
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - apk add git bash

stages:
  - mirror

mirror:
  stage: mirror
  script:
    - bash .mirror.sh
